[colors]
foreground=@@TEXT@@
background=@@BASE@@

## Normal colors
regular0=@@SURFACE1@@
regular1=@@RED@@
regular2=@@GREEN@@
regular3=@@YELLOW@@
regular4=@@BLUE@@
regular5=@@MAUVE@@
regular6=@@TEAL@@
regular7=@@SUBTEXT1@@

## Bright colors
bright0=@@SURFACE2@@
bright1=@@RED@@
bright2=@@GREEN@@
bright3=@@YELLOW@@
bright4=@@BLUE@@
bright5=@@MAUVE@@
bright6=@@TEAL@@
bright7=@@SUBTEXT0@@
